server:
  port: 8082

spring:
  application:
    name: basket

  datasource:
    url: jdbc:mysql://localhost:3306/basket
    username: root
    password: hSelMan%231?!
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    allow-circular-references: true
