server:
  port: 8083

spring:
  application:
    name: payment

  datasource:
    url: jdbc:mysql://localhost:3306/payment
    username: root
    password: hSelMan%231?!
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    allow-circular-references: true